# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastrar_evento.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from banco import Acesso_banco


class Ui_Dialog10(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(400, 82)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/enfermagem.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(90, 10, 291, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(18, 12, 71, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(81, 44, 220, 23))
        self.pushButton.setObjectName("pushButton")

        # ÍCONE DE VISTO
        self.btnIconeVistoConcluir = QtWidgets.QPushButton(Dialog)
        self.btnIconeVistoConcluir.setGeometry(QtCore.QRect(305, 40, 33, 33))
        self.btnIconeVistoConcluir.setAutoDefault(False)
        self.btnIconeVistoConcluir.setObjectName("btnIconeVistoConcluir")
        self.iconVistoConcluir = QtGui.QIcon()
        self.iconVistoConcluir.addPixmap(QtGui.QPixmap("img/visto.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnIconeVistoConcluir.setIcon(self.iconVistoConcluir)
        self.btnIconeVistoConcluir.setIconSize(QtCore.QSize(40, 40))
        self.btnIconeVistoConcluir.hide()

        # ÍCONE DE ERRO
        self.btnIconeErradoConcluir = QtWidgets.QPushButton(Dialog)
        self.btnIconeErradoConcluir.setGeometry(QtCore.QRect(305, 40, 30, 30))
        self.btnIconeErradoConcluir.setAutoDefault(False)
        self.btnIconeErradoConcluir.setObjectName("btnIconeErradoConcluir")
        self.iconErradoConcluir = QtGui.QIcon()
        self.iconErradoConcluir.addPixmap(QtGui.QPixmap("img/errado4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnIconeErradoConcluir.setIcon(self.iconErradoConcluir)
        self.btnIconeErradoConcluir.setIconSize(QtCore.QSize(55, 55))
        self.btnIconeErradoConcluir.hide()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        #Conectando-se ao banco
        self.banco = Acesso_banco.Banco_de_dados()
        self.banco.conectar()

        #Chamando método de gravar evento através do botão
        self.pushButton.clicked.connect(self.grava_evento)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "SISTEMA AMBULATÓRIO - CADASTRAR EVENTO"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">EVENTO:</span></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "CADASTRAR"))

    def grava_evento(self):
        evento = self.lineEdit.text()
        try:
            if evento != "":
                self.btnIconeVistoConcluir.show()
                self.banco.cadastrar_evento(evento)
                self.limpa_campo()
            else:
                self.btnIconeErradoConcluir.show()
                self.limpa_campo()
        except:
            self.btnIconeErradoConcluir.show()

    def limpa_campo(self):
        self.lineEdit.clear()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog10()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
