# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from inicio import Ui_Dialog
from banco import Acesso_banco
import os


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(443, 249)
        MainWindow.setAutoFillBackground(True)
        iconTela = QtGui.QIcon()
        iconTela.addFile("img/enfermagem.png")
        MainWindow.setWindowIcon(iconTela)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(34, 50, 381, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.edtLogin = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.edtLogin.setMinimumSize(QtCore.QSize(316, 0))
        self.edtLogin.setObjectName("edtLogin")
        self.horizontalLayout.addWidget(self.edtLogin)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.edtSenha = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.edtSenha.setObjectName("edtSenha")
        self.horizontalLayout_2.addWidget(self.edtSenha)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnLogar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnLogar.setObjectName("btnLogar")
        self.horizontalLayout_3.addWidget(self.btnLogar)
        self.btnLimpar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnLimpar.setObjectName("btnLimpar")
        self.horizontalLayout_3.addWidget(self.btnLimpar)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 20, 281, 41))
        self.label_3.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 433, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.edtLogin, self.edtSenha)
        MainWindow.setTabOrder(self.edtSenha, self.btnLogar)
        MainWindow.setTabOrder(self.btnLogar, self.btnLimpar)

        # Acessando o banco de dados
        self.banco = Acesso_banco.Banco_de_dados()
        self.banco.conectar()

        #Este botão limpa os campos de login e senha
        self.btnLimpar.clicked.connect(self.limparCampos)

        #O campo senha está com formato para não ver a senha claramente
        self.edtSenha.setEchoMode(self.edtSenha.Password)

        #Assim que a pessoa entrar com os dados corretos, entrará na tela inicial, caso dê errado, apresentará mensagem de "CREDENCIAIS INCORRETA"
        self.btnLogar.clicked.connect(self.logando)

        #Chamando o método que limita e formata os campos
        self.limitando_e_formatando_campos()



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SISTEMA AMBULATÓRIO"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Login</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Senha</span></p></body></html>"))
        self.btnLogar.setText(_translate("MainWindow", "LOGAR"))
        self.btnLimpar.setText(_translate("MainWindow", "LIMPAR"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">CONTROLE DE ACESSO</span></p></body></html>"))

    #Desabilita os campos e os botões da tela de login E depois disso abre a tela inicial
    def abrir_tela_inicial(self):
        telaInicial = QtWidgets.QDialog()
        ui = Ui_Dialog()
        ui.setupUi(telaInicial)
        self.limparCampos()
        self.desabilita_campos_e_botoes()
        MainWindow.hide()
        telaInicial.show()
        retorno = telaInicial.exec_()
        if retorno == 0:
            MainWindow.show()
            self.habilita_campos()

    #EVENTO PARA LIMPAR CAMPOS
    def limparCampos(self):
        self.edtLogin.clear()
        self.edtSenha.clear()

    #EVENTO PARA DESABILITAR CAMPOS, ENQUANTO A TELA INICIAL ESTIVER ABERTA
    def desabilita_campos_e_botoes(self):
        self.edtLogin.setDisabled(True)
        self.edtSenha.setDisabled(True)
        self.btnLogar.setDisabled(True)
        self.btnLimpar.setDisabled(True)

    #EVENTO QUE HABILITA CAMPOS, QUANDO A TELA INICIAL ESTIVER FECHADA
    def habilita_campos(self):
        self.edtLogin.setDisabled(False)
        self.edtSenha.setDisabled(False)
        self.btnLogar.setDisabled(False)
        self.btnLimpar.setDisabled(False)

    #EVENTO QUE LIMITA E FORMATA OS CAMPOS LOGIN E SENHA
    def limitando_e_formatando_campos(self):
        self.edtLogin.setMaxLength(11)
        self.edtSenha.setMaxLength(11)

    #EVENTO QUE LOGA NO SISTEMA
    def logando(self):
        conta = {}
        conta['usuario'] = self.edtLogin.text()
        conta['senha'] = self.edtSenha.text()
        verifica = self.banco.login_profissional(conta)
        if verifica != []:
            #Armazenei os dados do médico/enfermeiro numa variável de ambiente para usar no arquivo 'ficha_atendimento.py'
            os.environ["codigo"] = str(verifica)
            self.abrir_tela_inicial()
        else:
            self.statusbar = QtWidgets.QStatusBar(MainWindow)
            self.statusbar.setObjectName("statusbar")
            self.statusbar.showMessage("Credenciais Incorreta")
            MainWindow.setStatusBar(self.statusbar)




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
