# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastro_profissional.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from banco import Acesso_banco


class Ui_Dialog8(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(461, 197)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/enfermagem.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 10, 281, 20))
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 40, 441, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.edtNome = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.edtNome.setObjectName("edtNome")
        self.horizontalLayout.addWidget(self.edtNome)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(9, 80, 441, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.edtProfissao = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.edtProfissao.setObjectName("edtProfissao")
        self.horizontalLayout_2.addWidget(self.edtProfissao)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.edtRP = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.edtRP.setObjectName("edtRP")
        self.horizontalLayout_2.addWidget(self.edtRP)
        self.cmbRP = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.cmbRP.setObjectName("cmbRP")
        self.horizontalLayout_2.addWidget(self.cmbRP)
        self.btnCadastrar = QtWidgets.QPushButton(Dialog)
        self.btnCadastrar.setGeometry(QtCore.QRect(110, 130, 101, 51))
        self.btnCadastrar.setObjectName("btnCadastrar")
        self.btnLimpar = QtWidgets.QPushButton(Dialog)
        self.btnLimpar.setGeometry(QtCore.QRect(270, 130, 101, 51))
        self.btnLimpar.setObjectName("btnLimpar")

        # ÍCONE DE VISTO PARA O BOTÃO SALVAR
        self.btnIconeVisto = QtWidgets.QPushButton(Dialog)
        self.btnIconeVisto.setGeometry(QtCore.QRect(210, 140, 33, 33))
        self.btnIconeVisto.setAutoDefault(False)
        self.btnIconeVisto.setObjectName("btnIconeVisto")
        self.iconVisto = QtGui.QIcon()
        self.iconVisto.addPixmap(QtGui.QPixmap("img/visto.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnIconeVisto.setIcon(self.iconVisto)
        self.btnIconeVisto.setIconSize(QtCore.QSize(40, 40))
        self.btnIconeVisto.hide()

        # ÍCONE DE ERRO PARA O BOTÃO SALVAR
        self.btnIconeErrado = QtWidgets.QPushButton(Dialog)
        self.btnIconeErrado.setGeometry(QtCore.QRect(210, 140, 30, 30))
        self.btnIconeErrado.setAutoDefault(False)
        self.btnIconeErrado.setObjectName("btnIconeErrado")
        self.iconErrado = QtGui.QIcon()
        self.iconErrado.addPixmap(QtGui.QPixmap("img/errado4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnIconeErrado.setIcon(self.iconErrado)
        self.btnIconeErrado.setIconSize(QtCore.QSize(55, 55))
        self.btnIconeErrado.hide()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.edtNome, self.edtProfissao)
        Dialog.setTabOrder(self.edtProfissao, self.edtRP)
        Dialog.setTabOrder(self.edtRP, self.btnCadastrar)
        Dialog.setTabOrder(self.btnCadastrar, self.btnLimpar)

        #Conectando ao banco
        self.banco = Acesso_banco.Banco_de_dados()
        self.banco.conectar()

        #Formatando campo crm
        self.formata_campo()

        # Botão para cadastrar
        self.btnCadastrar.clicked.connect(self.cadastrar_profissional)

        #Botão para limpar os campos
        self.btnLimpar.clicked.connect(self.limpar_campos)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "SISTEMA AMBULATÓRIO - CADASTRO DO PROFISSIONAL"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">CADASTRO DO PROFISSIONAL</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<b>NOME:</b>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">PROFISSÃO:</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">RP:</span></p></body></html>"))
        self.btnCadastrar.setText(_translate("Dialog", "CADASTRAR"))
        self.btnLimpar.setText(_translate("Dialog", "LIMPAR"))

    #EVENTO QUE CADASTRA PROFISSIONAL
    def cadastrar_profissional(self):
        cadastro = {}
        cadastro['nome'] = self.edtNome.text()
        cadastro['profissao'] = self.edtProfissao.text()
        cadastro['rp'] = "("+self.cmbRP.currentText()+":"+self.edtRP.text()+")"
        try:
            if cadastro['nome'] != "" and cadastro['profissao'] != "" and cadastro['rp'] != "":
                if self.btnIconeErrado.isActiveWindow():
                    self.btnIconeErrado.hide()
                    self.banco.cadastrar_profissional(cadastro)
                    self.limpar_campos()
                    self.btnIconeVisto.show()
                else:
                    self.banco.cadastrar_profissional(cadastro)
                    self.limpar_campos()
                    self.btnIconeVisto.show()
            else:
                self.btnIconeErrado.show()
        except:
            self.btnIconeErrado.show()


    #EVENTO QUE FORMATA O CAMPO CRM
    def formata_campo(self):
        self.edtRP.setMaxLength(10)
        self.edtNome.setMaxLength(45)
        self.edtProfissao.setMaxLength(50)
        self.cmbRP.addItem("CRM")
        self.cmbRP.addItem("COREN")
        self.cmbRP.addItem("CRN")
        self.cmbRP.addItem("CRBM")
        self.cmbRP.addItem("CRFA")
        self.cmbRP.addItem("CRP")
        self.cmbRP.addItem("CRESS")
        self.cmbRP.addItem("CRF")
        self.cmbRP.addItem("CREFITO")
        self.cmbRP.addItem("T.O")


    #EVENTO QUE LIMPA OS CAMPOS
    def limpar_campos(self):
        self.edtNome.clear()
        self.edtProfissao.clear()
        self.edtRP.clear()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog8()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
